services:
  spring-server:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on: 
      - postgres
    networks:
      - mynet
    ports:
      - "8081:8080"
  postgres:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - myvolume:/var/lib/postgresql/data 
    networks:
      - mynet

volumes:
  myvolume:

networks:
  mynet:
    driver: bridge