name: Deploy to VM using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Build with Gradle
      run: ./gradlew build --no-daemon -x test

    - name: Add secrets to .env.prod
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
      run: |
        to_envs() {
          jq -r "to_entries[] | \"\(.key)=\(.value)\""
        }
        echo "$SECRETS_CONTEXT" | to_envs > .env.prod
        echo ENV_NAME=.env.prod >> .env.prod
        echo "Secrets added to .env.prod file."
        echo ".env.prod:"
        cat .env.prod

    - name: Get the last 8 digits of the commit hash
      run: |
        DOCKER_TAG=$(git rev-parse --short=8 HEAD)
        echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
        echo "DOCKER_TAG=$DOCKER_TAG" >> .env.prod
        echo "Using Docker tag: $DOCKER_TAG"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push (linux/amd64)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ranjabi/url-shortener-backend:latest,ranjabi/url-shortener-backend:${{ env.DOCKER_TAG }}
        platform: linux/amd64